= Grundlagen

== Aufgabe 1

=== TAS Tests
Alle Produkte in meiner Firme werden neben anderen Testmethoden auch mit TAS-Tests überprüft. Das heisst, das mit ansonsten fertige Produkt wird auf das Ziel Gerät geladen und die mit TAS-Tests werden laufen gelasse. Das Ziel der Tests ist es alle funktionen und Zustände während der Laufzeit zu Prüfen. Bei uns ist es so, dass die Tests ein eigenes Projekt sind, welches meistens mit pytest implementiert wird. Diese Tests greifen nicht auf den source code zu, weshalb das letzendliche Produkt prüfen und nicht wie Pipelines oder Unit Tests den Code.

=== Unit Testing
Bei Unit Tests geht es darum die geschriebenen Methoden anhand deren Rückgabe zu Prüfen. Normalerweise sollte man mindestens 50% des Codes mit Unit Tests abgedeckt haben. Die Unit Tests werde genutzt um zu überprüfen, ob ein Build erfolgreich war.

=== CI-CD
Bei der CI-CD Pipeline geht es vor allem nochmals darum das Project mit Unit Tests und meistens auch den Code Style zu überprüfen, bevor es auf git gepushed wird oder auf ein Gerät geladen wird.

== Aufgabe 2
=== SW-Fehler
Ein Software fehler könnte beispielsweise sein, dass ein Log file nicht erstellt wird wegen einem Fehler im Code.

=== SW-Magel 
Ein Software Mangel könnte sein, dass im Log File der falsche oder kein Name angegeben wird.

== Aufgabe 3
