= Test-Levels

== Aufgabe 1

=== Component Testing

Für das Component Testing verwendet meine Firma Unit-Tests und viele Code Reviews. Bei den Unit-Tests ist generell, die Regel, dass sie zuerst geschrieben werden sollten. Also wenn Möglich sollte der Test-Driven Weg genommen werden. Zudem müssen min 50% des Codes von Unit-Tests abgedekt sein.

Für die Tests werden sehr oft Mocks verwednet. Das heisst wenn Möglich erstellt man für verwendete classes ein interface, für welches man dann in dem test project ein Mock dazu schreiben kann.

=== Integration Testing

Bei den Integration Tests bin ich nicht involviert.

=== System Testing

Beim System Testing werden bei meiner Firma TAS Tests, verwendet, die soweit alle funktionen des Codes abdeken und auch integrierte Stress-Tests haben. 

Bei weiteren Tests bin ich nicht integriert.

=== Acceptance Testing

Bei den Acceptance Testing bin ich nicht involviert.


== Aufgabe 2

=== Testing approach

Der Testing approach ist der Weg wie man ans testen herangeht. Dazu gehört zum Beipiel ob man die Tests im vornerein schreibt oder man die Tests erst schreibt sobald die Application fertig ist.

=== Testing levels

Die verschiedenen Levels sind:

- Unit-Testing
- integration Testing
- system testing
- acceptance testing

=== Testing types, techniques and tactics

Bei dem geht es darum, wie man tested. Beispiele dafür sind, dass ob man Black- oder WhiteBox Tests duchführt oder als Beispiel sich auf automated testing fokusiert. Welche Frameworks und Umgebungen man nutzt, wer die Tests durchführt und so weiter. 

Das heisst dies fasst ein bisschen alles Andere zusammen und erstellt einen Plan um die Test durchzuführen, die alles umfassen.
